name: Build and Deploy Dev

on:
  push:
    branches:
      - main

jobs:
  trigger-dev-workflow:
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      environment: dev
    secrets: inherit